name: Deploy Storybook
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --legacy-peer-deps
      - run: npm run build-storybook
      - name: Deploy Storybook
      - run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GITHUB_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
